AWSTemplateFormatVersion: '2010-09-09'
Description: 'Product Video Generator - Load Balancer (Step 3 - ALB and Networking)'

Parameters:
  ProjectName:
    Type: String
    Default: product-video-generator
    Description: Project name used for naming resources
    AllowedPattern: '[a-zA-Z0-9-]+'
    ConstraintDescription: Must contain only alphanumeric characters and hyphens

  Environment:
    Type: String
    Default: prod
    AllowedValues: [dev, staging, prod]
    Description: Environment name

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where ALB will be deployed
    
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of public subnet IDs for ALB (minimum 2 subnets in different AZs)
    
  CertificateArn:
    Type: String
    Description: |
      ACM certificate ARN for HTTPS listener. Options:
      1. Leave empty for HTTP-only deployment (port 80 only)
      2. Use existing certificate ARN from this account
      3. Create certificate for subdomain (e.g., dev-app.example.com, staging-app.example.com)
      4. For cross-account certificates, must first share or recreate in this account
      Note: Certificate must be in the same region as this deployment
    Default: ''
    
  AllowedCidr:
    Type: String
    Default: '0.0.0.0/0'
    Description: CIDR block allowed to access ALB (0.0.0.0/0 for public access)
    AllowedPattern: '^(\d{1,3}\.){3}\d{1,3}/\d{1,2}$'

  ECSSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Existing security group ID for ECS tasks

Conditions:
  HasCertificate: !Not 
    - !Equals 
      - !Ref CertificateArn
      - ""

Resources:
  # ========================================
  # Application Load Balancer
  # ========================================
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${ProjectName}-alb-sg-${Environment}'
      GroupDescription: Security group for Application Load Balancer
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref AllowedCidr
          Description: HTTP traffic from internet
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref AllowedCidr
          Description: HTTPS traffic from internet
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-alb-sg-${Environment}'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${ProjectName}-alb-${Environment}'
      Scheme: internet-facing
      Type: application
      IpAddressType: ipv4
      Subnets: !Ref SubnetIds
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-alb-${Environment}'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${ProjectName}-tg-${Environment}'
      Protocol: HTTP
      Port: 80
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckEnabled: true
      HealthCheckProtocol: HTTP
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-tg-${Environment}'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  HTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  HTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Condition: HasCertificate
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Protocol: HTTPS
      Port: 443
      Certificates:
        - CertificateArn: !Ref CertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  # Security Group Rule to allow ALB traffic to ECS tasks
  ECSSecurityGroupIngressRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref ECSSecurityGroupId
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      SourceSecurityGroupId: !Ref ALBSecurityGroup
      Description: !Sub 'HTTP traffic from ${ProjectName} ALB'

# ========================================
# Outputs
# ========================================
Outputs:
  LoadBalancerArn:
    Description: ARN of the Application Load Balancer
    Value: !Ref ApplicationLoadBalancer
    Export:
      Name: !Sub '${ProjectName}-${Environment}-ALB-ARN'

  LoadBalancerDNS:
    Description: DNS name of the Application Load Balancer
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub '${ProjectName}-${Environment}-ALB-DNS'

  TargetGroupArn:
    Description: ARN of the target group
    Value: !Ref TargetGroup
    Export:
      Name: !Sub '${ProjectName}-${Environment}-TG-ARN'

  ALBSecurityGroupId:
    Description: ID of the ALB security group
    Value: !Ref ALBSecurityGroup
    Export:
      Name: !Sub '${ProjectName}-${Environment}-ALB-SG'

  ApplicationURL:
    Description: URL to access the application
    Value: !Sub 'http://${ApplicationLoadBalancer.DNSName}'

  ApplicationHTTPSURL:
    Condition: HasCertificate
    Description: HTTPS URL to access the application
    Value: !Sub 'https://${ApplicationLoadBalancer.DNSName}'