AWSTemplateFormatVersion: '2010-09-09'
Description: 'Product Video Generator - IAM Roles (Step 4 - ECS Task Roles and Policies)'

Parameters:
  ProjectName:
    Type: String
    Default: product-video-generator
    Description: Project name used for naming resources
    AllowedPattern: '[a-zA-Z0-9-]+'
    ConstraintDescription: Must contain only alphanumeric characters and hyphens

  Environment:
    Type: String
    Default: prod
    AllowedValues: [dev, staging, prod]
    Description: Environment name

Resources:
  # ========================================
  # IAM Roles and Policies
  # ========================================
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-execution-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-task-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  TaskPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${ProjectName}-task-policy-${Environment}'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # Bedrock permissions for video generation
          - Effect: Allow
            Action:
              - bedrock:InvokeModel
              - bedrock:InvokeModelWithResponseStream
              - bedrock:StartAsyncInvoke
              - bedrock:GetAsyncInvoke
              - bedrock:ListAsyncInvokes
              - bedrock:StopAsyncInvoke
            Resource: '*'
          # S3 permissions for general access
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:GetObject
              - s3:GetObjectAcl
              - s3:DeleteObject
              - s3:ListBucket
              - s3:GetBucketLocation
              - s3:ListBucketMultipartUploads
              - s3:ListMultipartUploadParts
              - s3:AbortMultipartUpload
            Resource: '*'
          # Additional S3 permissions that Bedrock might need
          - Effect: Allow
            Action:
              - s3:CreateBucket
              - s3:GetBucketVersioning
              - s3:PutBucketVersioning
              - s3:GetBucketNotification
              - s3:PutBucketNotification
            Resource: '*'
          # CloudWatch Logs permissions
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
            Resource: '*'
      Roles:
        - !Ref TaskRole

# ========================================
# Outputs
# ========================================
Outputs:
  TaskExecutionRoleArn:
    Description: ARN of the ECS task execution role
    Value: !GetAtt TaskExecutionRole.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-Task-Execution-Role-ARN'

  TaskRoleArn:
    Description: ARN of the ECS task role
    Value: !GetAtt TaskRole.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-Task-Role-ARN'